# Generated by Django 3.2 on 2021-05-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popular',
            old_name='country_created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='popular',
            old_name='country_created_user',
            new_name='created_user',
        ),
        migrations.RenameField(
            model_name='popular',
            old_name='country_updated_date',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='popular',
            old_name='country_updated_user',
            new_name='updated_user',
        ),
    ]
