# Generated by Django 3.2 on 2021-05-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210502_1258'),
        ('popular', '0002_auto_20210504_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='products.products'),
            preserve_default=False,
        ),
    ]
