# Generated by Django 3.2 on 2021-04-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=75)),
                ('describton', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=100)),
                ('seller_phone', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
