# Generated by Django 3.2 on 2021-04-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(upload_to='seller_pic/'),
        ),
    ]
