# Generated by Django 3.2 on 2021-04-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_user', '0002_alter_seller_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='describton',
            new_name='seller_bio',
        ),
    ]
