# Generated by Django 3.2 on 2021-04-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_user', '0004_auto_20210428_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='website',
            field=models.URLField(default='https://www.book.com'),
            preserve_default=False,
        ),
    ]
