# Generated by Django 3.2 on 2021-05-02 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_remove_countries_ads_price'),
        ('cities', '0001_initial'),
        ('seller_user', '0005_alter_seller_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='seller',
            name='city_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='cities.cities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='country_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='countries.countries'),
            preserve_default=False,
        ),
    ]
