# Generated by Django 3.2 on 2021-05-04 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('seller_user', '0006_auto_20210502_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='area_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='area.area'),
            preserve_default=False,
        ),
    ]
