# Generated by Django 3.2 on 2021-05-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_categories_category_title'),
        ('seller_user', '0007_seller_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='categories.categories'),
            preserve_default=False,
        ),
    ]
