# Generated by Django 3.2 on 2021-05-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_user', '0008_seller_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_phone',
        ),
    ]
