# Generated by Django 3.2 on 2021-09-01 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller_user', '0010_seller_is_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='seller_bio',
            new_name='about',
        ),
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='users.customuser'),
            preserve_default=False,
        ),
    ]
