# Generated by Django 3.2 on 2021-09-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_user', '0011_auto_20210901_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
