# Generated by Django 3.2 on 2021-09-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_user', '0012_alter_seller_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='area_name',
        ),
    ]
