# Generated by Django 3.2 on 2021-05-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productkeyword', '0002_auto_20210510_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_keyword',
            name='keyword_title',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='product_keyword',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
