# Generated by Django 3.2 on 2021-04-28 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recently_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recently_view',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='users.customuser'),
            preserve_default=False,
        ),
    ]
