# Generated by Django 3.2 on 2021-06-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recently_view', '0002_recently_view_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recently_view',
            name='view_at',
            field=models.DateField(auto_now=True),
        ),
    ]
