# Generated by Django 3.2 on 2021-06-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(default='sdfdsf', max_length=75, unique=True),
            preserve_default=False,
        ),
    ]
