# Generated by Django 3.2 on 2021-06-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=75)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
