# Generated by Django 3.2 on 2021-07-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
