# Generated by Django 3.2 on 2021-11-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('copun_text', models.CharField(default='', max_length=75)),
                ('copun_value', models.IntegerField(default=0)),
                ('copun_status', models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default=('active', 'active'), max_length=25)),
            ],
        ),
    ]
