# Generated by Django 3.2 on 2021-08-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20210502_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='shoppingcart_id',
            new_name='shopping_cart_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
