# Generated by Django 3.2 on 2021-11-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchase_shopping_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='shopping_cart_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='shopping_cart_product',
        ),
    ]
