# Generated by Django 3.2 on 2021-04-28 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=25)),
                ('country_name', models.CharField(default='', max_length=75)),
                ('phone_code', models.CharField(default='', max_length=25)),
                ('ads_price', models.FloatField(default=0.0)),
                ('country_created_date', models.DateField(auto_now=True)),
                ('country_updated_date', models.DateField(auto_now=True)),
                ('country_created_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('country_language_code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='languages.languages')),
                ('country_updated_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
