# Generated by Django 3.2 on 2021-05-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_remove_countries_ads_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country_name',
            field=models.CharField(default='', max_length=75, unique=True),
        ),
    ]
