# Generated by Django 3.2 on 2021-05-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_alter_countries_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='code',
            field=models.CharField(default='', max_length=5, unique=True),
        ),
    ]
