# Generated by Django 3.2 on 2021-05-02 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0005_alter_countries_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities', '0002_alter_cities_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(default='', max_length=75, unique=True)),
                ('area_created_date', models.DateField(auto_now=True)),
                ('area_updated_date', models.DateField(auto_now=True)),
                ('area_created_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('area_updated_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='cities.cities')),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='countries.countries')),
            ],
        ),
    ]
