# Generated by Django 3.2 on 2021-04-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('discount', models.FloatField(default=0.0)),
                ('expired', models.BooleanField(default=False, null=True)),
                ('numof_redem', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.URLField()),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products_title', to='products.products')),
            ],
        ),
    ]
