# Generated by Django 3.2 on 2021-04-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
