# Generated by Django 3.2 on 2021-06-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20210502_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
