# Generated by Django 3.2 on 2021-06-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20210601_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
