# Generated by Django 3.2 on 2021-06-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20210603_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='numof_redem',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='start_at',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='updated_at',
        ),
    ]
