# Generated by Django 3.2 on 2021-06-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_auto_20210606_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
