# Generated by Django 3.2 on 2021-06-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20210606_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='numof_redem',
            field=models.IntegerField(default=0),
        ),
    ]
