# Generated by Django 3.2 on 2021-04-28 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(default='', max_length=75)),
                ('city_created_date', models.DateField(auto_now=True)),
                ('city_updated_date', models.DateField(auto_now=True)),
                ('city_created_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('city_updated_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='countries.countries')),
            ],
        ),
    ]
