# Generated by Django 3.2 on 2021-09-05 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0002_alter_cities_city_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('area', '0001_initial'),
        ('countries', '0005_alter_countries_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=75)),
                ('about', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='buyer_pic/')),
                ('address', models.CharField(default='', max_length=125)),
                ('is_archive', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='area.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='cities.cities')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='countries.countries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
