# Generated by Django 3.2 on 2021-06-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20210502_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
