# Generated by Django 3.2 on 2021-04-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_image',
            field=models.ImageField(upload_to='category_pic'),
        ),
    ]
