# Generated by Django 3.2 on 2021-08-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_categories_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
