# Generated by Django 3.2 on 2021-04-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now=True)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.products')),
            ],
        ),
    ]
