# Generated by Django 3.2 on 2021-06-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_favorite_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='added_at',
            field=models.DateField(auto_now=True),
        ),
    ]
