# Generated by Django 3.2 on 2021-06-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0003_alter_favorite_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='added_at',
        ),
    ]
