# Generated by Django 3.2 on 2021-05-02 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210502_1258'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='products_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='products.products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='users.customuser'),
            preserve_default=False,
        ),
    ]
