# Generated by Django 3.2 on 2021-05-29 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_cart', '0002_auto_20210502_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='created_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='updated_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='users.customuser'),
            preserve_default=False,
        ),
    ]
