# Generated by Django 3.2 on 2021-06-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_auto_20210529_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
