# Generated by Django 3.2 on 2021-09-11 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_auto_20210911_1922'),
        ('shopping_cart', '0004_shopping_cart_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_cart_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='products.products')),
                ('shopping_cart_product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='shopping_cart.shopping_cart')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
