# Generated by Django 3.2 on 2021-04-28 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymentcurrency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcurrency',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentcurrency',
            name='created_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentcurrency',
            name='currency_code',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='paymentcurrency',
            name='currency_name',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='paymentcurrency',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentcurrency',
            name='updated_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
