# Generated by Django 3.2 on 2021-11-18 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copun', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_cart', '0008_alter_shopping_cart_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('delivering', 'delivering'), ('delivered', 'delivered')], default=('pending', 'pending'), max_length=25)),
                ('order_payment_option', models.CharField(choices=[('cach', 'cach'), ('visa', 'visa')], default=('cach', 'cach'), max_length=15)),
                ('order_amount', models.FloatField(default=0.0)),
                ('is_archived', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shopping_cart.shopping_cart')),
                ('order_copun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='copun.copun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
