# Generated by Django 3.2 on 2021-04-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('send_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(default='', max_length=50, unique=True)),
                ('describtion', models.CharField(max_length=200)),
                ('readed', models.BooleanField(default=False)),
            ],
        ),
    ]
