# Generated by Django 3.2 on 2021-05-02 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noti', '0002_alter_noti_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noti',
            old_name='describtion',
            new_name='descripstion',
        ),
        migrations.AddField(
            model_name='noti',
            name='created_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='users.customuser'),
            preserve_default=False,
        ),
    ]
