# Generated by Django 3.2 on 2021-05-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0003_auto_20210502_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noti',
            old_name='descripstion',
            new_name='dscription',
        ),
    ]
