# Generated by Django 3.2 on 2021-05-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0004_rename_descripstion_noti_dscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noti',
            old_name='dscription',
            new_name='description',
        ),
    ]
