# Generated by Django 3.2 on 2021-04-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('payment_type', models.CharField(max_length=25)),
                ('transactions_data', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shoppingcart_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shopping_cart.shopping_cart')),
            ],
        ),
    ]
