# Generated by Django 3.2 on 2021-04-28 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymentcurrency', '0002_auto_20210428_1647'),
        ('paymentoptions', '0002_auto_20210428_1647'),
        ('payment_transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='created_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='paymentcurrency.paymentcurrency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_options',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='paymentoptions.paymentoption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='users.customuser'),
            preserve_default=False,
        ),
    ]
