# Generated by Django 3.2 on 2021-04-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(default='', max_length=75)),
                ('product_describton', models.CharField(max_length=225)),
                ('product_price', models.FloatField(default=0.0)),
                ('product_hight', models.IntegerField(default=0)),
                ('product_width', models.IntegerField(default=0)),
                ('product_weight', models.FloatField(default=0.0)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_title', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='categories.categories')),
            ],
        ),
    ]
