# Generated by Django 3.2 on 2021-04-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_user', '0002_alter_seller_image'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seller_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='seller_user.seller'),
            preserve_default=False,
        ),
    ]
