# Generated by Django 3.2 on 2021-04-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_describton',
            new_name='product_description',
        ),
    ]
