# Generated by Django 3.2 on 2021-05-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_categories_category_title'),
        ('products', '0004_auto_20210502_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='categories.categories'),
        ),
    ]
