# Generated by Django 3.2 on 2021-05-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category_title',
            new_name='category_id',
        ),
    ]
