# Generated by Django 3.2 on 2021-05-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productkeyword', '0003_auto_20210510_1641'),
        ('products', '0006_rename_category_title_products_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='keyword_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='productkeyword.product_keyword'),
            preserve_default=False,
        ),
    ]
